Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                            count
---------------------------  -------
all                                1
picard_mark_duplicates             6
samtools_markdup_processing        6
total                             13

Resources before job selection: {'_cores': 24, '_nodes': 9223372036854775807}
Ready jobs (6)
Select jobs to execute...
Selected jobs (4)
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775803}
Execute 4 jobs...

[Thu Aug 15 16:45:41 2024]
Job 14: WT_REP2_control: Sorting and indexing alignments
Reason: Missing output files: results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam


[Thu Aug 15 16:45:41 2024]
Job 17: RAP1_REP2_treatment: Sorting and indexing alignments
Reason: Missing output files: results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam


[Thu Aug 15 16:45:41 2024]
Job 16: RAP1_REP1_treatment: Sorting and indexing alignments
Reason: Missing output files: results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 604, in __rule_picard_mark_duplicates
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/WT_REP2_control/WT_REP2_control.sorted.bam         --OUTPUT results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/WT_REP2_control.markduplicates.log' returned non-zero exit status 127.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 604, in __rule_picard_mark_duplicates
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/RAP1_REP2_treatment/RAP1_REP2_treatment.sorted.bam         --OUTPUT results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/RAP1_REP2_treatment.markduplicates.log' returned non-zero exit status 127.


Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 604, in __rule_picard_mark_duplicates
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/WT_REP2_control/WT_REP2_control.sorted.bam         --OUTPUT results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/WT_REP2_control.markduplicates.log' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 312:
Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/WT_REP2_control/WT_REP2_control.sorted.bam         --OUTPUT results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/WT_REP2_control.markduplicates.log' returned non-zero exit status 127.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 604, in __rule_picard_mark_duplicates
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/RAP1_REP1_treatment/RAP1_REP1_treatment.sorted.bam         --OUTPUT results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/RAP1_REP1_treatment.markduplicates.log' returned non-zero exit status 127.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 604, in __rule_picard_mark_duplicates
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/RAP1_REP2_treatment/RAP1_REP2_treatment.sorted.bam         --OUTPUT results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/RAP1_REP2_treatment.markduplicates.log' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 312:
Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/RAP1_REP2_treatment/RAP1_REP2_treatment.sorted.bam         --OUTPUT results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/RAP1_REP2_treatment.markduplicates.log' returned non-zero exit status 127.

[Thu Aug 15 16:45:41 2024]
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 604, in __rule_picard_mark_duplicates
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/RAP1_REP1_treatment/RAP1_REP1_treatment.sorted.bam         --OUTPUT results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/RAP1_REP1_treatment.markduplicates.log' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 312:
Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/RAP1_REP1_treatment/RAP1_REP1_treatment.sorted.bam         --OUTPUT results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/RAP1_REP1_treatment.markduplicates.log' returned non-zero exit status 127.

Job 13: WT_REP1_control: Sorting and indexing alignments
RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 312:
Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/RAP1_REP2_treatment/RAP1_REP2_treatment.sorted.bam         --OUTPUT results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/RAP1_REP2_treatment/RAP1_REP2_treatment.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/RAP1_REP2_treatment.markduplicates.log' returned non-zero exit status 127.
RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 312:
Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/WT_REP2_control/WT_REP2_control.sorted.bam         --OUTPUT results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/WT_REP2_control/WT_REP2_control.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/WT_REP2_control.markduplicates.log' returned non-zero exit status 127.
Reason: Missing output files: results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam
RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 312:
Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/RAP1_REP1_treatment/RAP1_REP1_treatment.sorted.bam         --OUTPUT results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/RAP1_REP1_treatment/RAP1_REP1_treatment.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/RAP1_REP1_treatment.markduplicates.log' returned non-zero exit status 127.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 604, in __rule_picard_mark_duplicates
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/WT_REP1_control/WT_REP1_control.sorted.bam         --OUTPUT results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/WT_REP1_control.markduplicates.log' returned non-zero exit status 127.

Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 423, in run_wrapper
    run(
  File "/home/lucianhu/rna_snakemake/test_ting/Snakefile", line 604, in __rule_picard_mark_duplicates
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/shell.py", line 357, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/WT_REP1_control/WT_REP1_control.sorted.bam         --OUTPUT results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/WT_REP1_control.markduplicates.log' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 261, in _callback
    raise ex
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 247, in cached_or_run
    run_func(*args)
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/executors/local.py", line 459, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 312:
Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/WT_REP1_control/WT_REP1_control.sorted.bam         --OUTPUT results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/WT_REP1_control.markduplicates.log' returned non-zero exit status 127.

RuleException:
CalledProcessError in file /home/lucianhu/rna_snakemake/test_ting/Snakefile, line 312:
Command 'set -euo pipefail;  
        picard -Xmx29491M MarkDuplicates         --ASSUME_SORTED true         --REMOVE_DUPLICATES false         --VALIDATION_STRINGENCY LENIENT         --TMP_DIR tmp         --INPUT results/align/bam_original/WT_REP1_control/WT_REP1_control.sorted.bam         --OUTPUT results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.bam         --REFERENCE_SEQUENCE resources/genome.fa         --METRICS_FILE results/align/bam_markup/WT_REP1_control/WT_REP1_control.markdup.sorted.MarkDuplicates.metrics.txt         &> logs/markdup/WT_REP1_control.markduplicates.log' returned non-zero exit status 127.
Terminating processes on user request, this might take some time.
Complete log: .snakemake/log/2024-08-15T164541.239657.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/cli.py", line 2103, in args_to_api
    dag_api.execute_workflow(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/api.py", line 594, in execute_workflow
    workflow.execute(
  File "/home/lucianhu/micromamba/envs/rna_snakemake/lib/python3.12/site-packages/snakemake/workflow.py", line 1286, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
